### ISSUE TITLE
Create `matrix-python-common` and pull out some common code from Sy* projects.

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/matrix-python-common#1]
The module cookiecutter template might actually be a good starting point; though you'd want to cut out the Synapse module-related fluff (but keep the CI, linting, etc?).

**Comment by H-Shay** [comment]
Noting common function `_reject_invalid_json` in both synapse and sygnal

**Comment by DMRobertson** [comment]
I suggest we raise an issue for each thing we identify as being duplicated.

**Comment by reivilibre** [comment]
Going to close this because the momentum has started and we're now at the point of raising individual issues for things we want to see done — thanks!
